language: android
android:
  components:
    - platform-tools
    - tools
    - android-23
    - build-tools-23.0.2
    - extra-android-support
    - extra-android-m2repository
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.gradle
script:
  - ./gradlew build
after_success:
notifications:
  email:
    recipients:
      - martinpurita@gmail.com
